export const GET_RESTAURANTS_REQUESTED = 'GET_RESTAURANTS_REQUESTED';
export const GET_RESTAURANTS_SUCCESS = 'GET_RESTAURANTS_SUCCESS';
export const GET_RESTAURANTS_FAILED='GET_RESTAURANTS_FAILED';


export const GET_RESTAURANTSTYPES_REQUESTED = 'GET_RESTAURANTSTYPES_REQUESTED';
export const GET_RESTAURANTSTYPES_SUCCESS = 'GET_RESTAURANTSTYPES_SUCCESS';
export const GET_RESTAURANTSTYPES_FAILED='GET_RESTAURANTSTYPES_FAILED';

export const GET_VISITEDRESTAURANTS_REQUESTED = 'GET_VISITEDRESTAURANTS_REQUESTED';
export const GET_VISITEDRESTAURANTS_SUCCESS = 'GET_VISITEDRESTAURANTS_SUCCESS';
export const GET_VISITEDRESTAURANTS_FAILED='GET_VISITEDRESTAURANTS_FAILED';

export const POST_VISITEDRESTAURANTS_REQUESTED = 'POST_VISITEDRESTAURANTS_REQUESTED';
export const POST_VISITEDRESTAURANTS_SUCCESS = 'POST_VISITEDRESTAURANTS_SUCCESS';
export const POST_VISITEDRESTAURANTS_FAILED='POST_VISITEDRESTAURANTS_FAILED';

export const DELETE_VISITEDRESTAURANTS_REQUESTED = 'DELETE_VISITEDRESTAURANTS_REQUESTED';
export const DELETE_VISITEDRESTAURANTS_SUCCESS = 'DELETE_VISITEDRESTAURANTS_SUCCESS';
export const DELETE_VISITEDRESTAURANTS_FAILED='DELETE_VISITEDRESTAURANTS_FAILED';